# Generated by Django 2.2.7 on 2019-12-01 13:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import donutsender.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('preferable_currency', models.CharField(default='BYN', max_length=3)),
                ('minimum_donate_sum', models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.1000000000000000055511151231257827021181583404541015625'))])),
                ('bio', models.CharField(default='Write a message to your donators :)', max_length=1000)),
                ('button_text', models.CharField(default='Send', max_length=50)),
                ('message_max_length', models.PositiveIntegerField(default=300, validators=[django.core.validators.MaxValueValidator(1000)])),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', donutsender.core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('money', models.DecimalField(decimal_places=2, default=5, max_digits=12)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments_from_me', to='core.User')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments_to_me', to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_is_enabled', models.BooleanField(default=True)),
                ('pop_up_is_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.User')),
            ],
        ),
    ]
