# Generated by Django 2.2.7 on 2019-12-03 16:26

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191201_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='from_name',
            field=models.CharField(default='Anonymous', help_text='Required. 20 characters or fewer.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator]),
        ),
    ]
