# Generated by Django 2.2.7 on 2019-12-07 16:04

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191203_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='message_max_length',
        ),
        migrations.RemoveField(
            model_name='user',
            name='minimum_donate_sum',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferable_currency',
        ),
        migrations.CreateModel(
            name='PaymentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='background_images/')),
                ('preferable_currency', models.CharField(default='BYN', max_length=3)),
                ('minimum_donate_sum', models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.1000000000000000055511151231257827021181583404541015625'))])),
                ('bio', models.CharField(default='Write a message to your donators :)', max_length=1000)),
                ('button_text', models.CharField(default='Send', max_length=50)),
                ('message_max_length', models.PositiveIntegerField(default=300, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
