# Generated by Django 2.2.7 on 2019-12-07 16:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191207_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpage',
            name='minimum_donate_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.1000000000000000055511151231257827021181583404541015625'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.1000000000000000055511151231257827021181583404541015625'))]),
        ),
        migrations.AlterField(
            model_name='paymentpage',
            name='preferable_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
