# Generated by Django 2.2.7 on 2019-12-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191208_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={'verbose_name_plural': 'cash register'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name_plural': 'notifications'},
        ),
    ]
