# Generated by Django 2.2.7 on 2019-12-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191212_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_withdraw_is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_withdraw',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
