# Generated by Django 2.2.7 on 2019-12-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191214_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='to_name',
            field=models.CharField(default='Lost', max_length=50),
        ),
    ]
