# Generated by Django 2.2.7 on 2019-12-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_firebaseuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebaseuser',
            name='firebase_token',
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='email',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='expiresIn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='idToken',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='kind',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='localId',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='refreshToken',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
