# Generated by Django 2.2.7 on 2019-12-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_payment_to_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='pop_up_is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
