# Generated by Django 2.2.7 on 2019-12-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191218_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseuser',
            name='localId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
