# Generated by Django 2.2.7 on 2019-12-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191218_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firebaseuser',
            old_name='idToken',
            new_name='firebase_token',
        ),
        migrations.RemoveField(
            model_name='firebaseuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='firebaseuser',
            name='expiresIn',
        ),
        migrations.RemoveField(
            model_name='firebaseuser',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='firebaseuser',
            name='localId',
        ),
        migrations.RemoveField(
            model_name='firebaseuser',
            name='refreshToken',
        ),
    ]
